baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kelvin Martin’s Sketchy Stuff'

[taxonomies]
    category = 'categories'

[caches]
    [caches.images]
        dir    = ':cacheDir/galleriesdeluxe'
        maxAge = "4320h"                     # 6 months.

[params]
    summaryLength = 20

    [params.author]
        name        = "Kelvin Martin"
        email       = "contact@alistair-martin.com"
        description = "A gallery website to display the work of Kelvin Martin."

    [params.galleriesdeluxe]
        # One of dartsass or libsass.
        sass_transpiler = "dartsass"

[params.gallerydeluxe]
    shuffle     = false
    reverse     = false
    enable_exif = false

[module]
    [[module.mounts]]
        source = "assets"
        target = "assets"
    [[module.mounts]]
        source = "content"
        target = "content"

    [[module.imports]]
        path = "github.com/bep/galleriesdeluxe"